# Generated by Django 5.0.2 on 2024-02-23 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_remove_bookclub_member_list_member_delete_memberlist"),
        ("users", "0002_profile_email_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="book_club",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.bookclub",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bookclub_admin",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
