# Generated by Django 5.0.2 on 2024-02-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_remove_bookclub_member_list_member_delete_memberlist"),
        ("users", "0003_profile_book_club_profile_bookclub_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="read_list",
            field=models.ManyToManyField(
                blank=True, related_name="finished", to="base.book"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="reading_list",
            field=models.ManyToManyField(
                blank=True, related_name="currently_reading", to="base.book"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tbr_list",
            field=models.ManyToManyField(
                blank=True, related_name="to_be_read", to="base.book"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="book_club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.bookclub",
            ),
        ),
    ]
