# Generated by Django 5.0.2 on 2024-02-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_notification"),
        ("users", "0004_profile_read_list_profile_reading_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notifications_list",
            field=models.ManyToManyField(blank=True, to="base.notification"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="read_list",
            field=models.ManyToManyField(
                blank=True, related_name="read_list", to="base.book"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="reading_list",
            field=models.ManyToManyField(
                blank=True, related_name="reading_list", to="base.book"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tbr_list",
            field=models.ManyToManyField(
                blank=True, related_name="tbr_list", to="base.book"
            ),
        ),
    ]
