# Generated by Django 5.0.2 on 2024-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_notifications_list_alter_profile_read_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="img_url",
            field=models.CharField(
                default="https://png.pngtree.com/background/20230519/original/pngtree-girl-reading-books-in-a-picture-picture-image_2658551.jpg"
            ),
        ),
    ]
