# Generated by Django 5.0.2 on 2024-02-23 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_bookclub_discussion_list_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookclub",
            name="link_id",
            field=models.CharField(default=models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="num_posts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
