# Generated by Django 5.0.2 on 2024-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_bookclub_link_id_alter_discussion_last_update_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookclub",
            name="discussion_list_id",
        ),
        migrations.AlterField(
            model_name="bookclub",
            name="link_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
